#!/usr/bin/env node
/**
 * Refreshes src/data/bundledModels.js from the canonical model catalog
 * served by araviel-api (which in turn proxies ADE's /api/v1/models).
 *
 * Behaviour:
 *   - Fetches the catalog, adapts the upstream shape into web's runtime
 *     shape (per-million pricing, short capability flag names, derived
 *     speedTier, web's nested context object), and writes the result
 *     into src/data/bundledModels.js.
 *   - Marketing copy (tagline, bestFor, badge) is owned by web and
 *     lives in src/data/modelPresentation.js — this script never
 *     touches it.
 *   - By default a network failure is non-fatal: the existing committed
 *     bundle is kept so local builds keep working offline. Set
 *     SYNC_MODELS_STRICT=true to fail the process (recommended for CI).
 *
 * Env vars:
 *   MODELS_CATALOG_URL    Override the catalog endpoint URL.
 *                         Defaults to production araviel-api.
 *   SYNC_MODELS_STRICT    "true" → exit 1 on fetch failure.
 *                         Anything else → keep existing bundle.
 */

import { writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const FETCH_TIMEOUT_MS = 15_000;

const DEFAULT_CATALOG_URL = 'https://api.araviel.ai/api/models/catalog';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const OUTPUT_PATH = join(__dirname, '..', 'src', 'data', 'bundledModels.js');

const CATALOG_URL = process.env.MODELS_CATALOG_URL || DEFAULT_CATALOG_URL;
const STRICT = process.env.SYNC_MODELS_STRICT === 'true';

function getSpeedTier(latencyMs) {
  if (latencyMs <= 500) return 'fast';
  if (latencyMs <= 1500) return 'balanced';
  return 'powerful';
}

function roundPrice(value) {
  return Math.round(value * 10000) / 10000;
}

function adaptModel(upstream) {
  return {
    id: upstream.id,
    name: upstream.name,
    provider: upstream.provider,
    description: upstream.description,
    speedTier: getSpeedTier(upstream.performance.avgLatencyMs),
    pricing: {
      inputPerM: roundPrice(upstream.pricing.inputPer1k * 1000),
      outputPerM: roundPrice(upstream.pricing.outputPer1k * 1000),
    },
    context: {
      inputTokens: upstream.capabilities.maxInputTokens,
      outputTokens: upstream.capabilities.maxOutputTokens,
    },
    capabilities: {
      vision: upstream.capabilities.supportsVision,
      audio: upstream.capabilities.supportsAudio,
      extendedThinking: upstream.capabilities.supportsExtendedThinking,
      webSearch: upstream.capabilities.supportsWebSearch,
      functionCalling: upstream.capabilities.supportsFunctionCalling,
      streaming: upstream.capabilities.supportsStreaming,
      imageGeneration: upstream.capabilities.supportsImageGeneration,
      tts: upstream.capabilities.supportsTTS,
      stt: upstream.capabilities.supportsSTT,
    },
    accessTier: upstream.accessTier,
    creditCost: upstream.creditCost,
  };
}

function renderBundleFile(models, sourceUrl, syncedAt) {
  const body = JSON.stringify(models, null, 2);
  return `/**
 * AUTO-GENERATED by scripts/sync-models.mjs.
 * Do NOT edit by hand — run \`npm run sync-models\` to refresh.
 *
 * Source:  ${sourceUrl}
 * Synced:  ${syncedAt}
 * Models:  ${models.length}
 */
export const BUNDLED_MODELS = ${body};

export const BUNDLED_MODELS_SYNCED_AT = ${JSON.stringify(syncedAt)};
`;
}

async function fetchCatalog(url) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
  try {
    const res = await fetch(url, { signal: controller.signal });
    if (!res.ok) {
      throw new Error(`Catalog endpoint returned HTTP ${res.status}`);
    }
    const body = await res.json();
    if (!Array.isArray(body?.models)) {
      throw new Error('Catalog endpoint returned a malformed body');
    }
    return body.models;
  } finally {
    clearTimeout(timer);
  }
}

function handleFailure(reason) {
  const hasExistingBundle = existsSync(OUTPUT_PATH);
  if (STRICT) {
    console.error(`[sync-models] ${reason}`);
    console.error('[sync-models] SYNC_MODELS_STRICT is set — failing.');
    process.exit(1);
  }
  if (!hasExistingBundle) {
    console.error(`[sync-models] ${reason}`);
    console.error('[sync-models] No existing bundle to fall back to — failing.');
    process.exit(1);
  }
  console.warn(`[sync-models] ${reason}`);
  console.warn(`[sync-models] Keeping existing bundle at ${OUTPUT_PATH}.`);
}

async function main() {
  console.log(`[sync-models] Fetching ${CATALOG_URL}`);
  let upstreamModels;
  try {
    upstreamModels = await fetchCatalog(CATALOG_URL);
  } catch (err) {
    handleFailure(`Fetch failed: ${err.message}`);
    return;
  }

  const adapted = upstreamModels.map(adaptModel);
  const syncedAt = new Date().toISOString();
  const file = renderBundleFile(adapted, CATALOG_URL, syncedAt);
  writeFileSync(OUTPUT_PATH, file);
  console.log(`[sync-models] Wrote ${adapted.length} models to ${OUTPUT_PATH}`);
}

main().catch((err) => {
  handleFailure(`Unexpected error: ${err.message}`);
});
